// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 143:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ======================================================================================
 * 5.用户登出
 * ======================================================================================
 */
public final class LogoutRequest extends Message<LogoutRequest, LogoutRequest.Builder> {
  public static final ProtoAdapter<LogoutRequest> ADAPTER = new ProtoAdapter_LogoutRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_FCMTOKEN = "";

  /**
   * 客户端信息
   */
  @WireField(
      tag = 1,
      adapter = "com.live.videochat.module.api.protocol.ClientInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final ClientInfo clientInfo;

  /**
   * 设备信息
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.DeviceInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final DeviceInfo deviceInfo;

  /**
   * 用户信息
   */
  @WireField(
      tag = 3,
      adapter = "com.live.videochat.module.api.protocol.UserInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final UserInfo userInfo;

  /**
   * fcm token.
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String fcmToken;

  public LogoutRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, String fcmToken) {
    this(clientInfo, deviceInfo, userInfo, fcmToken, ByteString.EMPTY);
  }

  public LogoutRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, String fcmToken, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.clientInfo = clientInfo;
    this.deviceInfo = deviceInfo;
    this.userInfo = userInfo;
    this.fcmToken = fcmToken;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.clientInfo = clientInfo;
    builder.deviceInfo = deviceInfo;
    builder.userInfo = userInfo;
    builder.fcmToken = fcmToken;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LogoutRequest)) return false;
    LogoutRequest o = (LogoutRequest) other;
    return unknownFields().equals(o.unknownFields())
        && clientInfo.equals(o.clientInfo)
        && deviceInfo.equals(o.deviceInfo)
        && userInfo.equals(o.userInfo)
        && Internal.equals(fcmToken, o.fcmToken);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + clientInfo.hashCode();
      result = result * 37 + deviceInfo.hashCode();
      result = result * 37 + userInfo.hashCode();
      result = result * 37 + (fcmToken != null ? fcmToken.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", clientInfo=").append(clientInfo);
    builder.append(", deviceInfo=").append(deviceInfo);
    builder.append(", userInfo=").append(userInfo);
    if (fcmToken != null) builder.append(", fcmToken=").append(fcmToken);
    return builder.replace(0, 2, "LogoutRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LogoutRequest, Builder> {
    public ClientInfo clientInfo;

    public DeviceInfo deviceInfo;

    public UserInfo userInfo;

    public String fcmToken;

    public Builder() {
    }

    /**
     * 客户端信息
     */
    public Builder clientInfo(ClientInfo clientInfo) {
      this.clientInfo = clientInfo;
      return this;
    }

    /**
     * 设备信息
     */
    public Builder deviceInfo(DeviceInfo deviceInfo) {
      this.deviceInfo = deviceInfo;
      return this;
    }

    /**
     * 用户信息
     */
    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    /**
     * fcm token.
     */
    public Builder fcmToken(String fcmToken) {
      this.fcmToken = fcmToken;
      return this;
    }

    @Override
    public LogoutRequest build() {
      if (clientInfo == null
          || deviceInfo == null
          || userInfo == null) {
        throw Internal.missingRequiredFields(clientInfo, "clientInfo",
            deviceInfo, "deviceInfo",
            userInfo, "userInfo");
      }
      return new LogoutRequest(clientInfo, deviceInfo, userInfo, fcmToken, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LogoutRequest extends ProtoAdapter<LogoutRequest> {
    ProtoAdapter_LogoutRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, LogoutRequest.class);
    }

    @Override
    public int encodedSize(LogoutRequest value) {
      return ClientInfo.ADAPTER.encodedSizeWithTag(1, value.clientInfo)
          + DeviceInfo.ADAPTER.encodedSizeWithTag(2, value.deviceInfo)
          + UserInfo.ADAPTER.encodedSizeWithTag(3, value.userInfo)
          + (value.fcmToken != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.fcmToken) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, LogoutRequest value) throws IOException {
      ClientInfo.ADAPTER.encodeWithTag(writer, 1, value.clientInfo);
      DeviceInfo.ADAPTER.encodeWithTag(writer, 2, value.deviceInfo);
      UserInfo.ADAPTER.encodeWithTag(writer, 3, value.userInfo);
      if (value.fcmToken != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.fcmToken);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LogoutRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.clientInfo(ClientInfo.ADAPTER.decode(reader)); break;
          case 2: builder.deviceInfo(DeviceInfo.ADAPTER.decode(reader)); break;
          case 3: builder.userInfo(UserInfo.ADAPTER.decode(reader)); break;
          case 4: builder.fcmToken(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public LogoutRequest redact(LogoutRequest value) {
      Builder builder = value.newBuilder();
      builder.clientInfo = ClientInfo.ADAPTER.redact(builder.clientInfo);
      builder.deviceInfo = DeviceInfo.ADAPTER.redact(builder.deviceInfo);
      builder.userInfo = UserInfo.ADAPTER.redact(builder.userInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
