// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 350:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 响应
 */
public final class TranslateResponse extends Message<TranslateResponse, TranslateResponse.Builder> {
  public static final ProtoAdapter<TranslateResponse> ADAPTER = new ProtoAdapter_TranslateResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_STATUS = 0;

  public static final String DEFAULT_TRANSLATEDTEXT = "";

  /**
   * 返回状态:1：成功;-1：错误;
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer status;

  /**
   * 翻译后的文本
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String translatedText;

  public TranslateResponse(Integer status, String translatedText) {
    this(status, translatedText, ByteString.EMPTY);
  }

  public TranslateResponse(Integer status, String translatedText, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.status = status;
    this.translatedText = translatedText;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.status = status;
    builder.translatedText = translatedText;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TranslateResponse)) return false;
    TranslateResponse o = (TranslateResponse) other;
    return unknownFields().equals(o.unknownFields())
        && status.equals(o.status)
        && Internal.equals(translatedText, o.translatedText);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + status.hashCode();
      result = result * 37 + (translatedText != null ? translatedText.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", status=").append(status);
    if (translatedText != null) builder.append(", translatedText=").append(translatedText);
    return builder.replace(0, 2, "TranslateResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TranslateResponse, Builder> {
    public Integer status;

    public String translatedText;

    public Builder() {
    }

    /**
     * 返回状态:1：成功;-1：错误;
     */
    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    /**
     * 翻译后的文本
     */
    public Builder translatedText(String translatedText) {
      this.translatedText = translatedText;
      return this;
    }

    @Override
    public TranslateResponse build() {
      if (status == null) {
        throw Internal.missingRequiredFields(status, "status");
      }
      return new TranslateResponse(status, translatedText, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TranslateResponse extends ProtoAdapter<TranslateResponse> {
    ProtoAdapter_TranslateResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, TranslateResponse.class);
    }

    @Override
    public int encodedSize(TranslateResponse value) {
      return ProtoAdapter.INT32.encodedSizeWithTag(1, value.status)
          + (value.translatedText != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.translatedText) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TranslateResponse value) throws IOException {
      ProtoAdapter.INT32.encodeWithTag(writer, 1, value.status);
      if (value.translatedText != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.translatedText);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TranslateResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.status(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.translatedText(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TranslateResponse redact(TranslateResponse value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
