// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 289:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * ======================================================================================
 * 8.账户服务(用户享有的服务，拥有的金币余额)
 * ======================================================================================
 * 请求
 */
public final class AccountServiceRequest extends Message<AccountServiceRequest, AccountServiceRequest.Builder> {
  public static final ProtoAdapter<AccountServiceRequest> ADAPTER = new ProtoAdapter_AccountServiceRequest();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ACTION = 0;

  /**
   * 客户端信息
   */
  @WireField(
      tag = 1,
      adapter = "com.live.videochat.module.api.protocol.ClientInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final ClientInfo clientInfo;

  /**
   * 设备信息
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.DeviceInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final DeviceInfo deviceInfo;

  /**
   * 验证登陆
   */
  @WireField(
      tag = 3,
      adapter = "com.live.videochat.module.api.protocol.UserInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final UserInfo userInfo;

  /**
   * 1:仅获取账户信息;2:获取目标jid的账户信息;3:获取账户明细
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer action;

  /**
   * 目标账户的jid；
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REPEATED
  )
  public final List<String> targetJid;

  public AccountServiceRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, Integer action, List<String> targetJid) {
    this(clientInfo, deviceInfo, userInfo, action, targetJid, ByteString.EMPTY);
  }

  public AccountServiceRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, Integer action, List<String> targetJid, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.clientInfo = clientInfo;
    this.deviceInfo = deviceInfo;
    this.userInfo = userInfo;
    this.action = action;
    this.targetJid = Internal.immutableCopyOf("targetJid", targetJid);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.clientInfo = clientInfo;
    builder.deviceInfo = deviceInfo;
    builder.userInfo = userInfo;
    builder.action = action;
    builder.targetJid = Internal.copyOf("targetJid", targetJid);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AccountServiceRequest)) return false;
    AccountServiceRequest o = (AccountServiceRequest) other;
    return unknownFields().equals(o.unknownFields())
        && clientInfo.equals(o.clientInfo)
        && deviceInfo.equals(o.deviceInfo)
        && userInfo.equals(o.userInfo)
        && action.equals(o.action)
        && targetJid.equals(o.targetJid);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + clientInfo.hashCode();
      result = result * 37 + deviceInfo.hashCode();
      result = result * 37 + userInfo.hashCode();
      result = result * 37 + action.hashCode();
      result = result * 37 + targetJid.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", clientInfo=").append(clientInfo);
    builder.append(", deviceInfo=").append(deviceInfo);
    builder.append(", userInfo=").append(userInfo);
    builder.append(", action=").append(action);
    if (!targetJid.isEmpty()) builder.append(", targetJid=").append(targetJid);
    return builder.replace(0, 2, "AccountServiceRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AccountServiceRequest, Builder> {
    public ClientInfo clientInfo;

    public DeviceInfo deviceInfo;

    public UserInfo userInfo;

    public Integer action;

    public List<String> targetJid;

    public Builder() {
      targetJid = Internal.newMutableList();
    }

    /**
     * 客户端信息
     */
    public Builder clientInfo(ClientInfo clientInfo) {
      this.clientInfo = clientInfo;
      return this;
    }

    /**
     * 设备信息
     */
    public Builder deviceInfo(DeviceInfo deviceInfo) {
      this.deviceInfo = deviceInfo;
      return this;
    }

    /**
     * 验证登陆
     */
    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    /**
     * 1:仅获取账户信息;2:获取目标jid的账户信息;3:获取账户明细
     */
    public Builder action(Integer action) {
      this.action = action;
      return this;
    }

    /**
     * 目标账户的jid；
     */
    public Builder targetJid(List<String> targetJid) {
      Internal.checkElementsNotNull(targetJid);
      this.targetJid = targetJid;
      return this;
    }

    @Override
    public AccountServiceRequest build() {
      if (clientInfo == null
          || deviceInfo == null
          || userInfo == null
          || action == null) {
        throw Internal.missingRequiredFields(clientInfo, "clientInfo",
            deviceInfo, "deviceInfo",
            userInfo, "userInfo",
            action, "action");
      }
      return new AccountServiceRequest(clientInfo, deviceInfo, userInfo, action, targetJid, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AccountServiceRequest extends ProtoAdapter<AccountServiceRequest> {
    ProtoAdapter_AccountServiceRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, AccountServiceRequest.class);
    }

    @Override
    public int encodedSize(AccountServiceRequest value) {
      return ClientInfo.ADAPTER.encodedSizeWithTag(1, value.clientInfo)
          + DeviceInfo.ADAPTER.encodedSizeWithTag(2, value.deviceInfo)
          + UserInfo.ADAPTER.encodedSizeWithTag(3, value.userInfo)
          + ProtoAdapter.INT32.encodedSizeWithTag(4, value.action)
          + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(5, value.targetJid)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AccountServiceRequest value) throws IOException {
      ClientInfo.ADAPTER.encodeWithTag(writer, 1, value.clientInfo);
      DeviceInfo.ADAPTER.encodeWithTag(writer, 2, value.deviceInfo);
      UserInfo.ADAPTER.encodeWithTag(writer, 3, value.userInfo);
      ProtoAdapter.INT32.encodeWithTag(writer, 4, value.action);
      ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.targetJid);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AccountServiceRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.clientInfo(ClientInfo.ADAPTER.decode(reader)); break;
          case 2: builder.deviceInfo(DeviceInfo.ADAPTER.decode(reader)); break;
          case 3: builder.userInfo(UserInfo.ADAPTER.decode(reader)); break;
          case 4: builder.action(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.targetJid.add(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AccountServiceRequest redact(AccountServiceRequest value) {
      Builder builder = value.newBuilder();
      builder.clientInfo = ClientInfo.ADAPTER.redact(builder.clientInfo);
      builder.deviceInfo = DeviceInfo.ADAPTER.redact(builder.deviceInfo);
      builder.userInfo = UserInfo.ADAPTER.redact(builder.userInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
