// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 397:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class AnchorVCard extends Message<AnchorVCard, AnchorVCard.Builder> {
  public static final ProtoAdapter<AnchorVCard> ADAPTER = new ProtoAdapter_AnchorVCard();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_JID = "";

  public static final String DEFAULT_AVATARURL = "";

  public static final String DEFAULT_NICKNAME = "";

  public static final Integer DEFAULT_DAILYCHARMS = 0;

  public static final Integer DEFAULT_WEEKLYCHARMS = 0;

  /**
   * 主播jid
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String jid;

  /**
   * 用户头像
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String avatarUrl;

  /**
   * 用户昵称
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String nickName;

  /**
   * 日榜/周榜数据
   * 日魅力值
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer dailyCharms;

  /**
   * 周魅力值
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer weeklyCharms;

  public AnchorVCard(String jid, String avatarUrl, String nickName, Integer dailyCharms, Integer weeklyCharms) {
    this(jid, avatarUrl, nickName, dailyCharms, weeklyCharms, ByteString.EMPTY);
  }

  public AnchorVCard(String jid, String avatarUrl, String nickName, Integer dailyCharms, Integer weeklyCharms, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.jid = jid;
    this.avatarUrl = avatarUrl;
    this.nickName = nickName;
    this.dailyCharms = dailyCharms;
    this.weeklyCharms = weeklyCharms;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.jid = jid;
    builder.avatarUrl = avatarUrl;
    builder.nickName = nickName;
    builder.dailyCharms = dailyCharms;
    builder.weeklyCharms = weeklyCharms;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AnchorVCard)) return false;
    AnchorVCard o = (AnchorVCard) other;
    return unknownFields().equals(o.unknownFields())
        && jid.equals(o.jid)
        && Internal.equals(avatarUrl, o.avatarUrl)
        && Internal.equals(nickName, o.nickName)
        && Internal.equals(dailyCharms, o.dailyCharms)
        && Internal.equals(weeklyCharms, o.weeklyCharms);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + jid.hashCode();
      result = result * 37 + (avatarUrl != null ? avatarUrl.hashCode() : 0);
      result = result * 37 + (nickName != null ? nickName.hashCode() : 0);
      result = result * 37 + (dailyCharms != null ? dailyCharms.hashCode() : 0);
      result = result * 37 + (weeklyCharms != null ? weeklyCharms.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", jid=").append(jid);
    if (avatarUrl != null) builder.append(", avatarUrl=").append(avatarUrl);
    if (nickName != null) builder.append(", nickName=").append(nickName);
    if (dailyCharms != null) builder.append(", dailyCharms=").append(dailyCharms);
    if (weeklyCharms != null) builder.append(", weeklyCharms=").append(weeklyCharms);
    return builder.replace(0, 2, "AnchorVCard{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AnchorVCard, Builder> {
    public String jid;

    public String avatarUrl;

    public String nickName;

    public Integer dailyCharms;

    public Integer weeklyCharms;

    public Builder() {
    }

    /**
     * 主播jid
     */
    public Builder jid(String jid) {
      this.jid = jid;
      return this;
    }

    /**
     * 用户头像
     */
    public Builder avatarUrl(String avatarUrl) {
      this.avatarUrl = avatarUrl;
      return this;
    }

    /**
     * 用户昵称
     */
    public Builder nickName(String nickName) {
      this.nickName = nickName;
      return this;
    }

    /**
     * 日榜/周榜数据
     * 日魅力值
     */
    public Builder dailyCharms(Integer dailyCharms) {
      this.dailyCharms = dailyCharms;
      return this;
    }

    /**
     * 周魅力值
     */
    public Builder weeklyCharms(Integer weeklyCharms) {
      this.weeklyCharms = weeklyCharms;
      return this;
    }

    @Override
    public AnchorVCard build() {
      if (jid == null) {
        throw Internal.missingRequiredFields(jid, "jid");
      }
      return new AnchorVCard(jid, avatarUrl, nickName, dailyCharms, weeklyCharms, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AnchorVCard extends ProtoAdapter<AnchorVCard> {
    ProtoAdapter_AnchorVCard() {
      super(FieldEncoding.LENGTH_DELIMITED, AnchorVCard.class);
    }

    @Override
    public int encodedSize(AnchorVCard value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.jid)
          + (value.avatarUrl != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.avatarUrl) : 0)
          + (value.nickName != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.nickName) : 0)
          + (value.dailyCharms != null ? ProtoAdapter.INT32.encodedSizeWithTag(4, value.dailyCharms) : 0)
          + (value.weeklyCharms != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.weeklyCharms) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AnchorVCard value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.jid);
      if (value.avatarUrl != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.avatarUrl);
      if (value.nickName != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.nickName);
      if (value.dailyCharms != null) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.dailyCharms);
      if (value.weeklyCharms != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.weeklyCharms);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AnchorVCard decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.jid(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.avatarUrl(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.nickName(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.dailyCharms(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.weeklyCharms(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AnchorVCard redact(AnchorVCard value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
