// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 279:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 响应
 */
public final class IABVerifyResponse extends Message<IABVerifyResponse, IABVerifyResponse.Builder> {
  public static final ProtoAdapter<IABVerifyResponse> ADAPTER = new ProtoAdapter_IABVerifyResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_STATUS = 0;

  public static final Integer DEFAULT_OWNERTYPE = 0;

  /**
   * 返回状态:1：成功;-1：错误;
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer status;

  /**
   * 账户信息；
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.AccountInfo#ADAPTER"
  )
  public final AccountInfo accountInfo;

  /**
   * 商品的所有者的类型.1：已经使用过，是当前用户；2:已经使用，但不是当前用户；3：无人所有
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer ownerType;

  public IABVerifyResponse(Integer status, AccountInfo accountInfo, Integer ownerType) {
    this(status, accountInfo, ownerType, ByteString.EMPTY);
  }

  public IABVerifyResponse(Integer status, AccountInfo accountInfo, Integer ownerType, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.status = status;
    this.accountInfo = accountInfo;
    this.ownerType = ownerType;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.status = status;
    builder.accountInfo = accountInfo;
    builder.ownerType = ownerType;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof IABVerifyResponse)) return false;
    IABVerifyResponse o = (IABVerifyResponse) other;
    return unknownFields().equals(o.unknownFields())
        && status.equals(o.status)
        && Internal.equals(accountInfo, o.accountInfo)
        && Internal.equals(ownerType, o.ownerType);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + status.hashCode();
      result = result * 37 + (accountInfo != null ? accountInfo.hashCode() : 0);
      result = result * 37 + (ownerType != null ? ownerType.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", status=").append(status);
    if (accountInfo != null) builder.append(", accountInfo=").append(accountInfo);
    if (ownerType != null) builder.append(", ownerType=").append(ownerType);
    return builder.replace(0, 2, "IABVerifyResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<IABVerifyResponse, Builder> {
    public Integer status;

    public AccountInfo accountInfo;

    public Integer ownerType;

    public Builder() {
    }

    /**
     * 返回状态:1：成功;-1：错误;
     */
    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    /**
     * 账户信息；
     */
    public Builder accountInfo(AccountInfo accountInfo) {
      this.accountInfo = accountInfo;
      return this;
    }

    /**
     * 商品的所有者的类型.1：已经使用过，是当前用户；2:已经使用，但不是当前用户；3：无人所有
     */
    public Builder ownerType(Integer ownerType) {
      this.ownerType = ownerType;
      return this;
    }

    @Override
    public IABVerifyResponse build() {
      if (status == null) {
        throw Internal.missingRequiredFields(status, "status");
      }
      return new IABVerifyResponse(status, accountInfo, ownerType, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_IABVerifyResponse extends ProtoAdapter<IABVerifyResponse> {
    ProtoAdapter_IABVerifyResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, IABVerifyResponse.class);
    }

    @Override
    public int encodedSize(IABVerifyResponse value) {
      return ProtoAdapter.INT32.encodedSizeWithTag(1, value.status)
          + (value.accountInfo != null ? AccountInfo.ADAPTER.encodedSizeWithTag(2, value.accountInfo) : 0)
          + (value.ownerType != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.ownerType) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, IABVerifyResponse value) throws IOException {
      ProtoAdapter.INT32.encodeWithTag(writer, 1, value.status);
      if (value.accountInfo != null) AccountInfo.ADAPTER.encodeWithTag(writer, 2, value.accountInfo);
      if (value.ownerType != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.ownerType);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public IABVerifyResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.status(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.accountInfo(AccountInfo.ADAPTER.decode(reader)); break;
          case 3: builder.ownerType(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public IABVerifyResponse redact(IABVerifyResponse value) {
      Builder builder = value.newBuilder();
      if (builder.accountInfo != null) builder.accountInfo = AccountInfo.ADAPTER.redact(builder.accountInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
