// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 268:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ======================================================================================
 * 7.应用市场商品校验
 * ======================================================================================
 * 请求
 */
public final class IABVerifyRequest extends Message<IABVerifyRequest, IABVerifyRequest.Builder> {
  public static final ProtoAdapter<IABVerifyRequest> ADAPTER = new ProtoAdapter_IABVerifyRequest();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_SKU = "";

  public static final String DEFAULT_TYPE = "";

  public static final String DEFAULT_PURCHASETOKEN = "";

  public static final Integer DEFAULT_ACTION = 0;

  /**
   * 客户端信息
   */
  @WireField(
      tag = 1,
      adapter = "com.live.videochat.module.api.protocol.ClientInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final ClientInfo clientInfo;

  /**
   * 设备信息
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.DeviceInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final DeviceInfo deviceInfo;

  /**
   * 验证登陆
   */
  @WireField(
      tag = 3,
      adapter = "com.live.videochat.module.api.protocol.UserInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final UserInfo userInfo;

  /**
   * 商品编号
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String sku;

  /**
   * 商品类型, inapp:应用内商品，可管理的; subs:订阅类商品;当action为应用市场商品校验时必填。
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String type;

  /**
   * 商品购买凭证
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String purchaseToken;

  /**
   * 1:应用市场商品校验；2：商品所有者检测；
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer action;

  public IABVerifyRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, String sku, String type, String purchaseToken, Integer action) {
    this(clientInfo, deviceInfo, userInfo, sku, type, purchaseToken, action, ByteString.EMPTY);
  }

  public IABVerifyRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, String sku, String type, String purchaseToken, Integer action, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.clientInfo = clientInfo;
    this.deviceInfo = deviceInfo;
    this.userInfo = userInfo;
    this.sku = sku;
    this.type = type;
    this.purchaseToken = purchaseToken;
    this.action = action;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.clientInfo = clientInfo;
    builder.deviceInfo = deviceInfo;
    builder.userInfo = userInfo;
    builder.sku = sku;
    builder.type = type;
    builder.purchaseToken = purchaseToken;
    builder.action = action;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof IABVerifyRequest)) return false;
    IABVerifyRequest o = (IABVerifyRequest) other;
    return unknownFields().equals(o.unknownFields())
        && clientInfo.equals(o.clientInfo)
        && deviceInfo.equals(o.deviceInfo)
        && userInfo.equals(o.userInfo)
        && sku.equals(o.sku)
        && Internal.equals(type, o.type)
        && purchaseToken.equals(o.purchaseToken)
        && action.equals(o.action);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + clientInfo.hashCode();
      result = result * 37 + deviceInfo.hashCode();
      result = result * 37 + userInfo.hashCode();
      result = result * 37 + sku.hashCode();
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + purchaseToken.hashCode();
      result = result * 37 + action.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", clientInfo=").append(clientInfo);
    builder.append(", deviceInfo=").append(deviceInfo);
    builder.append(", userInfo=").append(userInfo);
    builder.append(", sku=").append(sku);
    if (type != null) builder.append(", type=").append(type);
    builder.append(", purchaseToken=").append(purchaseToken);
    builder.append(", action=").append(action);
    return builder.replace(0, 2, "IABVerifyRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<IABVerifyRequest, Builder> {
    public ClientInfo clientInfo;

    public DeviceInfo deviceInfo;

    public UserInfo userInfo;

    public String sku;

    public String type;

    public String purchaseToken;

    public Integer action;

    public Builder() {
    }

    /**
     * 客户端信息
     */
    public Builder clientInfo(ClientInfo clientInfo) {
      this.clientInfo = clientInfo;
      return this;
    }

    /**
     * 设备信息
     */
    public Builder deviceInfo(DeviceInfo deviceInfo) {
      this.deviceInfo = deviceInfo;
      return this;
    }

    /**
     * 验证登陆
     */
    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    /**
     * 商品编号
     */
    public Builder sku(String sku) {
      this.sku = sku;
      return this;
    }

    /**
     * 商品类型, inapp:应用内商品，可管理的; subs:订阅类商品;当action为应用市场商品校验时必填。
     */
    public Builder type(String type) {
      this.type = type;
      return this;
    }

    /**
     * 商品购买凭证
     */
    public Builder purchaseToken(String purchaseToken) {
      this.purchaseToken = purchaseToken;
      return this;
    }

    /**
     * 1:应用市场商品校验；2：商品所有者检测；
     */
    public Builder action(Integer action) {
      this.action = action;
      return this;
    }

    @Override
    public IABVerifyRequest build() {
      if (clientInfo == null
          || deviceInfo == null
          || userInfo == null
          || sku == null
          || purchaseToken == null
          || action == null) {
        throw Internal.missingRequiredFields(clientInfo, "clientInfo",
            deviceInfo, "deviceInfo",
            userInfo, "userInfo",
            sku, "sku",
            purchaseToken, "purchaseToken",
            action, "action");
      }
      return new IABVerifyRequest(clientInfo, deviceInfo, userInfo, sku, type, purchaseToken, action, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_IABVerifyRequest extends ProtoAdapter<IABVerifyRequest> {
    ProtoAdapter_IABVerifyRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, IABVerifyRequest.class);
    }

    @Override
    public int encodedSize(IABVerifyRequest value) {
      return ClientInfo.ADAPTER.encodedSizeWithTag(1, value.clientInfo)
          + DeviceInfo.ADAPTER.encodedSizeWithTag(2, value.deviceInfo)
          + UserInfo.ADAPTER.encodedSizeWithTag(3, value.userInfo)
          + ProtoAdapter.STRING.encodedSizeWithTag(4, value.sku)
          + (value.type != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.type) : 0)
          + ProtoAdapter.STRING.encodedSizeWithTag(6, value.purchaseToken)
          + ProtoAdapter.INT32.encodedSizeWithTag(7, value.action)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, IABVerifyRequest value) throws IOException {
      ClientInfo.ADAPTER.encodeWithTag(writer, 1, value.clientInfo);
      DeviceInfo.ADAPTER.encodeWithTag(writer, 2, value.deviceInfo);
      UserInfo.ADAPTER.encodeWithTag(writer, 3, value.userInfo);
      ProtoAdapter.STRING.encodeWithTag(writer, 4, value.sku);
      if (value.type != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.type);
      ProtoAdapter.STRING.encodeWithTag(writer, 6, value.purchaseToken);
      ProtoAdapter.INT32.encodeWithTag(writer, 7, value.action);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public IABVerifyRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.clientInfo(ClientInfo.ADAPTER.decode(reader)); break;
          case 2: builder.deviceInfo(DeviceInfo.ADAPTER.decode(reader)); break;
          case 3: builder.userInfo(UserInfo.ADAPTER.decode(reader)); break;
          case 4: builder.sku(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.type(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.purchaseToken(ProtoAdapter.STRING.decode(reader)); break;
          case 7: builder.action(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public IABVerifyRequest redact(IABVerifyRequest value) {
      Builder builder = value.newBuilder();
      builder.clientInfo = ClientInfo.ADAPTER.redact(builder.clientInfo);
      builder.deviceInfo = DeviceInfo.ADAPTER.redact(builder.deviceInfo);
      builder.userInfo = UserInfo.ADAPTER.redact(builder.userInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
