// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 358:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ======================================================================================
 * 11.排行榜
 * ======================================================================================
 */
public final class RankRequest extends Message<RankRequest, RankRequest.Builder> {
  public static final ProtoAdapter<RankRequest> ADAPTER = new ProtoAdapter_RankRequest();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_RANKTYPE = 0;

  public static final Integer DEFAULT_INDEX = 0;

  /**
   * 客户端信息
   */
  @WireField(
      tag = 1,
      adapter = "com.live.videochat.module.api.protocol.ClientInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final ClientInfo clientInfo;

  /**
   * 设备信息
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.DeviceInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final DeviceInfo deviceInfo;

  /**
   * 用户信息（jid, vcToken, role）
   */
  @WireField(
      tag = 3,
      adapter = "com.live.videochat.module.api.protocol.UserInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final UserInfo userInfo;

  /**
   * 排行榜类型:1:Top fans排行榜.2：土豪榜.3：魅力榜.4:最近充值排行榜.
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer rankType;

  /**
   * 分页索引，默认为0
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer index;

  public RankRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, Integer rankType, Integer index) {
    this(clientInfo, deviceInfo, userInfo, rankType, index, ByteString.EMPTY);
  }

  public RankRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, Integer rankType, Integer index, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.clientInfo = clientInfo;
    this.deviceInfo = deviceInfo;
    this.userInfo = userInfo;
    this.rankType = rankType;
    this.index = index;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.clientInfo = clientInfo;
    builder.deviceInfo = deviceInfo;
    builder.userInfo = userInfo;
    builder.rankType = rankType;
    builder.index = index;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RankRequest)) return false;
    RankRequest o = (RankRequest) other;
    return unknownFields().equals(o.unknownFields())
        && clientInfo.equals(o.clientInfo)
        && deviceInfo.equals(o.deviceInfo)
        && userInfo.equals(o.userInfo)
        && rankType.equals(o.rankType)
        && Internal.equals(index, o.index);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + clientInfo.hashCode();
      result = result * 37 + deviceInfo.hashCode();
      result = result * 37 + userInfo.hashCode();
      result = result * 37 + rankType.hashCode();
      result = result * 37 + (index != null ? index.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", clientInfo=").append(clientInfo);
    builder.append(", deviceInfo=").append(deviceInfo);
    builder.append(", userInfo=").append(userInfo);
    builder.append(", rankType=").append(rankType);
    if (index != null) builder.append(", index=").append(index);
    return builder.replace(0, 2, "RankRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RankRequest, Builder> {
    public ClientInfo clientInfo;

    public DeviceInfo deviceInfo;

    public UserInfo userInfo;

    public Integer rankType;

    public Integer index;

    public Builder() {
    }

    /**
     * 客户端信息
     */
    public Builder clientInfo(ClientInfo clientInfo) {
      this.clientInfo = clientInfo;
      return this;
    }

    /**
     * 设备信息
     */
    public Builder deviceInfo(DeviceInfo deviceInfo) {
      this.deviceInfo = deviceInfo;
      return this;
    }

    /**
     * 用户信息（jid, vcToken, role）
     */
    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    /**
     * 排行榜类型:1:Top fans排行榜.2：土豪榜.3：魅力榜.4:最近充值排行榜.
     */
    public Builder rankType(Integer rankType) {
      this.rankType = rankType;
      return this;
    }

    /**
     * 分页索引，默认为0
     */
    public Builder index(Integer index) {
      this.index = index;
      return this;
    }

    @Override
    public RankRequest build() {
      if (clientInfo == null
          || deviceInfo == null
          || userInfo == null
          || rankType == null) {
        throw Internal.missingRequiredFields(clientInfo, "clientInfo",
            deviceInfo, "deviceInfo",
            userInfo, "userInfo",
            rankType, "rankType");
      }
      return new RankRequest(clientInfo, deviceInfo, userInfo, rankType, index, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RankRequest extends ProtoAdapter<RankRequest> {
    ProtoAdapter_RankRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, RankRequest.class);
    }

    @Override
    public int encodedSize(RankRequest value) {
      return ClientInfo.ADAPTER.encodedSizeWithTag(1, value.clientInfo)
          + DeviceInfo.ADAPTER.encodedSizeWithTag(2, value.deviceInfo)
          + UserInfo.ADAPTER.encodedSizeWithTag(3, value.userInfo)
          + ProtoAdapter.INT32.encodedSizeWithTag(4, value.rankType)
          + (value.index != null ? ProtoAdapter.INT32.encodedSizeWithTag(5, value.index) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RankRequest value) throws IOException {
      ClientInfo.ADAPTER.encodeWithTag(writer, 1, value.clientInfo);
      DeviceInfo.ADAPTER.encodeWithTag(writer, 2, value.deviceInfo);
      UserInfo.ADAPTER.encodeWithTag(writer, 3, value.userInfo);
      ProtoAdapter.INT32.encodeWithTag(writer, 4, value.rankType);
      if (value.index != null) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.index);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RankRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.clientInfo(ClientInfo.ADAPTER.decode(reader)); break;
          case 2: builder.deviceInfo(DeviceInfo.ADAPTER.decode(reader)); break;
          case 3: builder.userInfo(UserInfo.ADAPTER.decode(reader)); break;
          case 4: builder.rankType(ProtoAdapter.INT32.decode(reader)); break;
          case 5: builder.index(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RankRequest redact(RankRequest value) {
      Builder builder = value.newBuilder();
      builder.clientInfo = ClientInfo.ADAPTER.redact(builder.clientInfo);
      builder.deviceInfo = DeviceInfo.ADAPTER.redact(builder.deviceInfo);
      builder.userInfo = UserInfo.ADAPTER.redact(builder.userInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
