// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 322:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ======================================================================================
 * 9.奖励接口(每日免费消息条数奖励)
 * ======================================================================================
 * 请求
 */
public final class RewardRequest extends Message<RewardRequest, RewardRequest.Builder> {
  public static final ProtoAdapter<RewardRequest> ADAPTER = new ProtoAdapter_RewardRequest();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_REWARDTYPE = 0;

  /**
   * 客户端信息
   */
  @WireField(
      tag = 1,
      adapter = "com.live.videochat.module.api.protocol.ClientInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final ClientInfo clientInfo;

  /**
   * 设备信息
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.DeviceInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final DeviceInfo deviceInfo;

  /**
   * 验证登陆
   */
  @WireField(
      tag = 3,
      adapter = "com.live.videochat.module.api.protocol.UserInfo#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final UserInfo userInfo;

  /**
   * 1:每日免费消息条数奖励;2:激活首次充值奖励
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer rewardType;

  public RewardRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, Integer rewardType) {
    this(clientInfo, deviceInfo, userInfo, rewardType, ByteString.EMPTY);
  }

  public RewardRequest(ClientInfo clientInfo, DeviceInfo deviceInfo, UserInfo userInfo, Integer rewardType, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.clientInfo = clientInfo;
    this.deviceInfo = deviceInfo;
    this.userInfo = userInfo;
    this.rewardType = rewardType;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.clientInfo = clientInfo;
    builder.deviceInfo = deviceInfo;
    builder.userInfo = userInfo;
    builder.rewardType = rewardType;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RewardRequest)) return false;
    RewardRequest o = (RewardRequest) other;
    return unknownFields().equals(o.unknownFields())
        && clientInfo.equals(o.clientInfo)
        && deviceInfo.equals(o.deviceInfo)
        && userInfo.equals(o.userInfo)
        && rewardType.equals(o.rewardType);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + clientInfo.hashCode();
      result = result * 37 + deviceInfo.hashCode();
      result = result * 37 + userInfo.hashCode();
      result = result * 37 + rewardType.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", clientInfo=").append(clientInfo);
    builder.append(", deviceInfo=").append(deviceInfo);
    builder.append(", userInfo=").append(userInfo);
    builder.append(", rewardType=").append(rewardType);
    return builder.replace(0, 2, "RewardRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<RewardRequest, Builder> {
    public ClientInfo clientInfo;

    public DeviceInfo deviceInfo;

    public UserInfo userInfo;

    public Integer rewardType;

    public Builder() {
    }

    /**
     * 客户端信息
     */
    public Builder clientInfo(ClientInfo clientInfo) {
      this.clientInfo = clientInfo;
      return this;
    }

    /**
     * 设备信息
     */
    public Builder deviceInfo(DeviceInfo deviceInfo) {
      this.deviceInfo = deviceInfo;
      return this;
    }

    /**
     * 验证登陆
     */
    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    /**
     * 1:每日免费消息条数奖励;2:激活首次充值奖励
     */
    public Builder rewardType(Integer rewardType) {
      this.rewardType = rewardType;
      return this;
    }

    @Override
    public RewardRequest build() {
      if (clientInfo == null
          || deviceInfo == null
          || userInfo == null
          || rewardType == null) {
        throw Internal.missingRequiredFields(clientInfo, "clientInfo",
            deviceInfo, "deviceInfo",
            userInfo, "userInfo",
            rewardType, "rewardType");
      }
      return new RewardRequest(clientInfo, deviceInfo, userInfo, rewardType, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_RewardRequest extends ProtoAdapter<RewardRequest> {
    ProtoAdapter_RewardRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, RewardRequest.class);
    }

    @Override
    public int encodedSize(RewardRequest value) {
      return ClientInfo.ADAPTER.encodedSizeWithTag(1, value.clientInfo)
          + DeviceInfo.ADAPTER.encodedSizeWithTag(2, value.deviceInfo)
          + UserInfo.ADAPTER.encodedSizeWithTag(3, value.userInfo)
          + ProtoAdapter.INT32.encodedSizeWithTag(4, value.rewardType)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, RewardRequest value) throws IOException {
      ClientInfo.ADAPTER.encodeWithTag(writer, 1, value.clientInfo);
      DeviceInfo.ADAPTER.encodeWithTag(writer, 2, value.deviceInfo);
      UserInfo.ADAPTER.encodeWithTag(writer, 3, value.userInfo);
      ProtoAdapter.INT32.encodeWithTag(writer, 4, value.rewardType);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public RewardRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.clientInfo(ClientInfo.ADAPTER.decode(reader)); break;
          case 2: builder.deviceInfo(DeviceInfo.ADAPTER.decode(reader)); break;
          case 3: builder.userInfo(UserInfo.ADAPTER.decode(reader)); break;
          case 4: builder.rewardType(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public RewardRequest redact(RewardRequest value) {
      Builder builder = value.newBuilder();
      builder.clientInfo = ClientInfo.ADAPTER.redact(builder.clientInfo);
      builder.deviceInfo = DeviceInfo.ADAPTER.redact(builder.deviceInfo);
      builder.userInfo = UserInfo.ADAPTER.redact(builder.userInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
