// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: VCProto.proto at 114:1
package com.live.videochat.module.api.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class LoginResponse extends Message<LoginResponse, LoginResponse.Builder> {
  public static final ProtoAdapter<LoginResponse> ADAPTER = new ProtoAdapter_LoginResponse();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_STATUS = 0;

  /**
   * 状态 1：成功； -1：错误
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer status;

  /**
   * 用户信息（jid, vcToken, role）
   */
  @WireField(
      tag = 2,
      adapter = "com.live.videochat.module.api.protocol.UserInfo#ADAPTER"
  )
  public final UserInfo userInfo;

  /**
   * xmpp各组件的信息
   */
  @WireField(
      tag = 3,
      adapter = "com.live.videochat.module.api.protocol.ComponentInfo#ADAPTER"
  )
  public final ComponentInfo componentInfo;

  public LoginResponse(Integer status, UserInfo userInfo, ComponentInfo componentInfo) {
    this(status, userInfo, componentInfo, ByteString.EMPTY);
  }

  public LoginResponse(Integer status, UserInfo userInfo, ComponentInfo componentInfo, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.status = status;
    this.userInfo = userInfo;
    this.componentInfo = componentInfo;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.status = status;
    builder.userInfo = userInfo;
    builder.componentInfo = componentInfo;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginResponse)) return false;
    LoginResponse o = (LoginResponse) other;
    return unknownFields().equals(o.unknownFields())
        && status.equals(o.status)
        && Internal.equals(userInfo, o.userInfo)
        && Internal.equals(componentInfo, o.componentInfo);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + status.hashCode();
      result = result * 37 + (userInfo != null ? userInfo.hashCode() : 0);
      result = result * 37 + (componentInfo != null ? componentInfo.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append(", status=").append(status);
    if (userInfo != null) builder.append(", userInfo=").append(userInfo);
    if (componentInfo != null) builder.append(", componentInfo=").append(componentInfo);
    return builder.replace(0, 2, "LoginResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<LoginResponse, Builder> {
    public Integer status;

    public UserInfo userInfo;

    public ComponentInfo componentInfo;

    public Builder() {
    }

    /**
     * 状态 1：成功； -1：错误
     */
    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    /**
     * 用户信息（jid, vcToken, role）
     */
    public Builder userInfo(UserInfo userInfo) {
      this.userInfo = userInfo;
      return this;
    }

    /**
     * xmpp各组件的信息
     */
    public Builder componentInfo(ComponentInfo componentInfo) {
      this.componentInfo = componentInfo;
      return this;
    }

    @Override
    public LoginResponse build() {
      if (status == null) {
        throw Internal.missingRequiredFields(status, "status");
      }
      return new LoginResponse(status, userInfo, componentInfo, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_LoginResponse extends ProtoAdapter<LoginResponse> {
    ProtoAdapter_LoginResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, LoginResponse.class);
    }

    @Override
    public int encodedSize(LoginResponse value) {
      return ProtoAdapter.INT32.encodedSizeWithTag(1, value.status)
          + (value.userInfo != null ? UserInfo.ADAPTER.encodedSizeWithTag(2, value.userInfo) : 0)
          + (value.componentInfo != null ? ComponentInfo.ADAPTER.encodedSizeWithTag(3, value.componentInfo) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, LoginResponse value) throws IOException {
      ProtoAdapter.INT32.encodeWithTag(writer, 1, value.status);
      if (value.userInfo != null) UserInfo.ADAPTER.encodeWithTag(writer, 2, value.userInfo);
      if (value.componentInfo != null) ComponentInfo.ADAPTER.encodeWithTag(writer, 3, value.componentInfo);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public LoginResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.status(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.userInfo(UserInfo.ADAPTER.decode(reader)); break;
          case 3: builder.componentInfo(ComponentInfo.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public LoginResponse redact(LoginResponse value) {
      Builder builder = value.newBuilder();
      if (builder.userInfo != null) builder.userInfo = UserInfo.ADAPTER.redact(builder.userInfo);
      if (builder.componentInfo != null) builder.componentInfo = ComponentInfo.ADAPTER.redact(builder.componentInfo);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
